databases:
  - name: llama-app-db
    databaseName: llama_app_db
    user: user
    region: singapore

services:
  # A Docker web service
  # Docs for Render blueprints:
  # https://render.com/docs/blueprint-spec
  - type: web
    name: llama-app-backend
    runtime: docker
    repo: https://github.com/rc-jeffrey-huang/sec-insights.git
    region: singapore
    plan: free
    rootDir: ./backend
    # https://render.com/docs/blueprint-spec#scaling
    scaling:
      minInstances: 2
      maxInstances: 10
      targetMemoryPercent: 75 # optional if targetCPUPercent is set (valid: 1-90)
      targetCPUPercent: 75 # optional if targetMemory is set (valid: 1-90)
    healthCheckPath: /api/health/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: llama-app-db
          property: connectionString
      - fromGroup: general-settings
      - fromGroup: prod-web-secrets

envVarGroups:
  - name: general-settings
    envVars:
      - key: IS_PREVIEW_ENV
        value: false
        previewValue: true
      - key: LOG_LEVEL
        value: INFO
        previewValue: DEBUG
      - key: BACKEND_CORS_ORIGINS
        value: '["http://localhost", "http://localhost:8000", "http://localhost:3000", "http://127.0.0.1:3000", "https://llama-app-backend.onrender.com", "https://llama-app-frontend.vercel.app", "http://secinsights.ai", "http://www.secinsights.ai", "https://secinsights.ai", "https://www.secinsights.ai"]'
      # S3_BUCKET_NAME is the bucket used for the StorageContext of the backend's LlamaIndex chat engine
      - key: S3_BUCKET_NAME
        value: llama-app-backend-prod
        previewValue: llama-app-backend-preview
      # S3_ASSET_BUCKET_NAME is the bucket used for app assets (e.g. document PDFs)
      - key: S3_ASSET_BUCKET_NAME
        value: llama-app-web-assets-prod
        previewValue: llama-app-web-assets-preview
      - key: CDN_BASE_URL
        value: https://d687lz8k56fia.cloudfront.net
        previewValue: https://dl94gqvzlh4k8.cloudfront.net
  - name: prod-web-secrets
    envVars:
      # Manually add a prod value for OPENAI_API_KEY in Render dashboard
      - key: OPENAI_API_KEY
        sync: false
      - key: AWS_KEY
        sync: false
      - key: AWS_SECRET
        sync: false
      - key: POLYGON_IO_API_KEY
        sync: false
