"""empty message

Revision ID: 2de2e101012c
Revises: 873c0c4616ea
Create Date: 2023-09-14 17:20:23.761567

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2de2e101012c"
down_revision = "873c0c4616ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "conversationdocument_document_id_fkey",
        "conversationdocument",
        type_="foreignkey",
    )
    op.drop_index("ix_document_id", table_name="document")
    op.drop_table("document", cascade="all")
    op.drop_table("data_pg_vector_store")
    op.drop_index(
        "ix_conversationdocument_document_id", table_name="conversationdocument"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "conversationdocument_document_id_fkey",
        "conversationdocument",
        "document",
        ["document_id"],
        ["id"],
    )
    op.create_index(
        "ix_conversationdocument_document_id",
        "conversationdocument",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "data_pg_vector_store",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "metadata_",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("node_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="data_pg_vector_store_pkey"),
    )
    op.create_table(
        "document",
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "metadata_map",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="document_pkey"),
        sa.UniqueConstraint("url", name="document_url_key"),
    )
    op.create_index("ix_document_id", "document", ["id"], unique=False)
    # ### end Alembic commands ###
