"""empty message

Revision ID: 47b5b41ca553
Revises: 95047618ece8
Create Date: 2023-09-14 17:47:11.020873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b5b41ca553'
down_revision = '95047618ece8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversationdocument', sa.Column('document_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversationdocument', 'document_id')
    # ### end Alembic commands ###
